// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PcollectorV2.Data;

#nullable disable

namespace PcollectorV2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PcollectorV2.Models.Card", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("BuyDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("BuyPrice")
                        .HasColumnType("float");

                    b.Property<int>("CollectionID")
                        .HasColumnType("int");

                    b.Property<string>("CollectionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CurrentPrice")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CollectionID");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BuyDate = new DateTime(2024, 9, 18, 14, 14, 36, 537, DateTimeKind.Local).AddTicks(928),
                            BuyPrice = 13.0,
                            CollectionID = 1,
                            CollectionName = "expensive",
                            Condition = "Mint Condition",
                            CurrentPrice = 23.0,
                            Description = "Met verpakking",
                            Name = "Test",
                            Specialty = "PSA 8"
                        });
                });

            modelBuilder.Entity("PcollectorV2.Models.Collection", b =>
                {
                    b.Property<int>("CollectionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CollectionID"));

                    b.Property<string>("CollectionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InventoryID")
                        .HasColumnType("int");

                    b.HasKey("CollectionID");

                    b.HasIndex("InventoryID");

                    b.ToTable("Collections");

                    b.HasData(
                        new
                        {
                            CollectionID = 1,
                            CollectionName = "Holo",
                            InventoryID = 0
                        });
                });

            modelBuilder.Entity("PcollectorV2.Models.Inventory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("PcollectorV2.Models.Card", b =>
                {
                    b.HasOne("PcollectorV2.Models.Collection", null)
                        .WithMany("Cards")
                        .HasForeignKey("CollectionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PcollectorV2.Models.Collection", b =>
                {
                    b.HasOne("PcollectorV2.Models.Inventory", "Inventory")
                        .WithMany("Collections")
                        .HasForeignKey("InventoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("PcollectorV2.Models.Collection", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("PcollectorV2.Models.Inventory", b =>
                {
                    b.Navigation("Collections");
                });
#pragma warning restore 612, 618
        }
    }
}
